## Extreme Learning Machine

In [1]:
import numpy as np

In [2]:
import math

In [3]:
from csv import reader
file = open('data 1.csv')
data = reader(file,delimiter=";")
data = list(data)

In [4]:
def exploredata(start,end,data):
    for baris in data[start:end]:
        print(baris)
    print("jumlah data :" ,len(data))
    print("jumlah kolom :" ,len(data[0]))   

In [5]:
# data[1:] dikarenakan data[0] merupakan header dari data tersebut
exploredata(0,5,data[41:55])

['586.091.416', '0.0668833', '0.45086673', '0.96311105', '172.733.556', '0.00447338', '1.262.138.007', '0.05401571', '0.32870513', '0.92058887', '172.733.556', '0.00447338', '3']
['553.590.858', '0.06725974', '0.45718758', '0.96668892', '168.369.008', '0.00452387', '1.195.002.293', '0.054619', '0.33672919', '0.92811089', '168.369.008', '0.00452387', '3']
['568.830.546', '0.06688525', '0.45580701', '0.96595108', '170.128.205', '0.00447364', '1.253.002.763', '0.05435134', '0.33490956', '0.92500305', '170.128.205', '0.00447364', '3']
['405.995.541', '0.07792213', '0.50627049', '0.97394237', '14.154.961', '0.00607186', '929.333.005', '0.06380138', '0.3823362', '0.94041554', '14.154.961', '0.00607186', '3']
['954.195.095', '0.05902701', '0.4043442', '0.95852679', '211.956.522', '0.00348419', '1.885.654.523', '0.04818549', '0.29499519', '0.91812373', '211.956.522', '0.00348419', '3']
jumlah data : 14
jumlah kolom : 13


In [6]:
for row in data:
    row[0] = row[0].replace(".","")
    row[4] = row[4].replace(".","")
    row[6] = row[6].replace(".","")
    row[10] = row[10].replace(".","")

In [7]:
def extractFitur(data):
    fitur = [x[:-1] for x in data]
    fitur  = np.asarray(fitur,dtype=float)
    return fitur

In [8]:
def extractTarget(data):
    target = [x[-1] for x in data]
    return target

In [9]:
def normalize(fitur):
    normalize=[]
    minz = np.min(fitur, axis=0)
    maxz = np.max(fitur, axis=0)
    for x in fitur:
        keren = (x-minz)/(maxz-minz)
        normalize.append(keren)
    return normalize

In [10]:
def MatriksHinit(fitur,weight):
    weight_t = weight.T
    h_init = np.dot(fitur,weight_t)
    return h_init

In [11]:
def SigmoidBiner(y):
    matriks = []
    for x in y[0:]:
        aktivasi = 1/(1+np.exp(-x))
        matriks.append(aktivasi)
    h = np.asarray(matriks,dtype=float)
    return h

In [12]:
def fungsilinier(y):
    matriks = []
    for x in y[0:]:
        aktivasi = x
        matriks.append(aktivasi)
    h = np.asarray(matriks,dtype=float)
    return h

In [13]:
def sigmoidbipolar(y):
    matriks = []
    for x in y[0:]:
        aktivasi = ((1-np.exp(-x))/(1+np.exp(-x)))
        matriks.append(aktivasi)
    h = np.asarray(matriks,dtype=float)
    return h

In [14]:
def sigmoidradialbasis(y):
    matriks = []
    for x in y[0:]:
        aktivasi = np.exp(-(x**2))
        matriks.append(aktivasi)
        h = np.asarray(matriks,dtype=float)
    return h

In [15]:
def matrikshplus(y):
    y_transpose = y.T
    perkalian = np.dot(y_transpose,y)
    inverse = np.linalg.inv(perkalian)
    hplus = np.dot(inverse,y_transpose)
    return hplus

In [16]:
fitur = extractFitur(data[1:])
target = extractTarget(data[1:])
fitur = normalize(fitur)

# Pengujian Berdasarkan Rasio Data Latih dan Data Uji

### Data Latih : Data Uji 70:30

In [17]:
datatraining = fitur[0:10]
datatraining.extend(fitur[10:20])
datatraining.extend(fitur[20:24])
datatraining.extend(fitur[30:34])
datatraining.extend(fitur[40:54])
targettrain = target[0:10]
targettrain.extend(target[10:20])
targettrain.extend(target[20:24])
targettrain.extend(target[30:34])
targettrain.extend(target[40:54])
targettrain  = np.asarray(targettrain,dtype=float)
print(len(datatraining))

42


In [18]:
datatesting = fitur[24:30]
datatesting.extend(fitur[34:40])
datatesting.extend(fitur[54:60])
targettest = target[24:30]
targettest.extend(target[34:40])
targettest.extend(target[54:60])
targettest  = np.asarray(targettest,dtype=float)
print(len(datatesting))

18


In [19]:
weight = [[-0.96679837,-0.56691479,-0.99709835,-0.46686085,-0.270499,0.08664495,-0.03301548,0.41532664,0.75242603,-0.65012204,0.59926752,-0.89635113]]
#np.random.uniform(-1,1,(1,12))
weight = np.asarray(weight,dtype=float)
print("weight \n",weight)

weight 
 [[-0.96679837 -0.56691479 -0.99709835 -0.46686085 -0.270499    0.08664495
  -0.03301548  0.41532664  0.75242603 -0.65012204  0.59926752 -0.89635113]]


##### Fungsi Aktivasi Dengan Sigmoid Biner

In [20]:
matrikshinit = MatriksHinit(datatraining,weight)
matriksh = SigmoidBiner(matrikshinit)
hplus = matrikshplus(matriksh)
betatopisigmoidbiner = np.dot(hplus,targettrain)
betatopisigmoidbiner

array([8.06550341])

In [21]:
matrikshinit = MatriksHinit(datatesting,weight)
matriksh = SigmoidBiner(matrikshinit)
yprediksisigmoidbiner = np.dot(matriksh,betatopisigmoidbiner)
print(yprediksisigmoidbiner)
Mape = 0
for x,y in zip(yprediksisigmoidbiner,targettest):
    Mape = Mape + abs(((x-y)/y)*100)
print(targettest)
print("Mape = ",Mape/len(targettest))

[1.45859015 1.48155751 1.4702738  1.30895756 1.37004571 1.58919459
 1.2087001  1.38173769 1.32935619 1.3573914  0.82191427 1.45970044
 3.24564916 1.96621851 2.00004228 2.05846201 2.26701744 1.82456147]
[2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3.]
Mape =  29.363579838805567


### Data Latih : Data Uji 60:40

In [22]:
datatraining = fitur[0:10]
datatraining.extend(fitur[10:20])
datatraining.extend(fitur[20:22])
datatraining.extend(fitur[30:32])
datatraining.extend(fitur[40:52])
targettrain = target[0:10]
targettrain.extend(target[10:20])
targettrain.extend(target[20:22])
targettrain.extend(target[30:32])
targettrain.extend(target[40:52])
targettrain  = np.asarray(targettrain,dtype=float)
print(len(datatraining))

36


In [23]:
datatesting = fitur[22:30]
datatesting.extend(fitur[32:40])
datatesting.extend(fitur[52:60])
targettest = target[22:30]
targettest.extend(target[32:40])
targettest.extend(target[52:60])
targettest  = np.asarray(targettest,dtype=float)
print(len(datatesting))

24


##### Fungsi Aktivasi Dengan Sigmoid Biner

In [24]:
matrikshinit = MatriksHinit(datatraining,weight)
matriksh = SigmoidBiner(matrikshinit)
hplus = matrikshplus(matriksh)
betatopisigmoidbiner = np.dot(hplus,targettrain)
betatopisigmoidbiner

array([7.8636333])

In [25]:
matrikshinit = MatriksHinit(datatesting,weight)
matriksh = SigmoidBiner(matrikshinit)
yprediksisigmoidbiner = np.dot(matriksh,betatopisigmoidbiner)
print(yprediksisigmoidbiner)
Mape = 0
for x,y in zip(yprediksisigmoidbiner,targettest):
    Mape = Mape + abs(((x-y)/y)*100)
print(targettest)
print("Mape = ",Mape/len(targettest))

[1.5879081  1.64295355 1.42208334 1.44447585 1.43347457 1.27619588
 1.33575507 1.54941891 1.36700948 1.1950547  1.17844775 1.34715441
 1.29608396 1.32341748 0.80134272 1.42316584 2.44008917 2.15198759
 3.16441436 1.91700637 1.94998356 2.00694112 2.21027665 1.77889483]
[2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3.]
Mape =  27.996958182111314


# Pengujian Berdasarkan Fungsi Aktivasi

### Fungsi Aktivasi Dengan Sigmoid Biner

In [26]:
matrikshinit = MatriksHinit(datatraining,weight)
matriksh = SigmoidBiner(matrikshinit)
hplus = matrikshplus(matriksh)
betatopisigmoidbiner = np.dot(hplus,targettrain)
betatopisigmoidbiner

array([7.8636333])

In [27]:
matrikshinit = MatriksHinit(datatesting,weight)
matriksh = SigmoidBiner(matrikshinit)
yprediksisigmoidbiner = np.dot(matriksh,betatopisigmoidbiner)
print(yprediksisigmoidbiner)
Mape = 0
for x,y in zip(yprediksisigmoidbiner,targettest):
    Mape = Mape + abs(((x-y)/y)*100)
print(targettest)
print("Mape = ",Mape/len(targettest))

[1.5879081  1.64295355 1.42208334 1.44447585 1.43347457 1.27619588
 1.33575507 1.54941891 1.36700948 1.1950547  1.17844775 1.34715441
 1.29608396 1.32341748 0.80134272 1.42316584 2.44008917 2.15198759
 3.16441436 1.91700637 1.94998356 2.00694112 2.21027665 1.77889483]
[2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3.]
Mape =  27.996958182111314


### Fungsi Aktivasi Dengan Fungsi Linier

In [28]:
matrikshinit = MatriksHinit(datatraining,weight)
matriksh = fungsilinier(matrikshinit)
hplus = matrikshplus(matriksh)
betatopilinier = np.dot(hplus,targettrain)
betatopilinier

array([-1.6069349])

In [29]:
matrikshinit = MatriksHinit(datatesting,weight)
matriksh = fungsilinier(matrikshinit)
yprediksifungsilinier = np.dot(matriksh,betatopilinier)
print(yprediksifungsilinier)
Mape = 0
for x,y in zip(yprediksifungsilinier,targettest):
    Mape = Mape + abs(((x-y)/y)*100)
print(targettest)
print(Mape/len(targettest))

[2.20836493 2.1394468  2.42751017 2.39680823 2.41184531 2.63743128
 2.54953919 2.25762041 2.50466055 2.76266623 2.78915025 2.53307521
 2.60772331 2.56748469 3.49706958 2.42601736 1.28348287 1.56855377
 0.63542755 1.81914571 1.78280148 1.72098427 1.50912363 1.9761948 ]
[2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3.]
79.59816237552168


### Fungsi Aktivasi Dengan Fungsi Sigmoid Bipolar

In [30]:
matrikshinit = MatriksHinit(datatraining,weight)
matriksh = sigmoidbipolar(matrikshinit)
hplus = matrikshplus(matriksh)
betatopisigmoidbipolar = np.dot(hplus,targettrain)
betatopisigmoidbipolar

array([-3.71128582])

In [31]:
matrikshinit = MatriksHinit(datatesting,weight)
matriksh = sigmoidbipolar(matrikshinit)
yprediksisigmoidbipolar = np.dot(matriksh,betatopisigmoidbipolar)
print(yprediksisigmoidbipolar)
Mape = 0
for x,y in zip(yprediksisigmoidbipolar,targettest):
    Mape = Mape + abs(((x-y)/y)*100)
print(targettest)
print(Mape/len(targettest))

[2.21244156 2.16048354 2.3689654  2.34782886 2.3582131  2.50667021
 2.45045164 2.24877194 2.42095024 2.58326029 2.59893577 2.43969166
 2.48789763 2.46209722 2.95488944 2.36794362 1.40805829 1.6800006
 0.72435963 1.90180202 1.87067447 1.8169116  1.62498091 2.03216704]
[2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3.]
72.03997568382867


### Fungsi Aktivasi Dengan Fungsi Sigmoid Radial Basis

In [32]:
matrikshinit = MatriksHinit(datatraining,weight)
matriksh = sigmoidradialbasis(matrikshinit)
hplus = matrikshplus(matriksh)
betatopisigmoidradialbasis = np.dot(hplus,targettrain)
betatopisigmoidradialbasis

array([4.90895682])

In [33]:
matriksh = sigmoidradialbasis(matrikshinit)
yprediksiradialbasis = np.dot(matriksh,betatopisigmoidradialbasis)
print(yprediksiradialbasis)
Mape = 0
for x,y in zip(yprediksiradialbasis,targettest):
    Mape = Mape + abs(((x-y)/y)*100)
print(targettest)
print(Mape/len(targettest))

[1.33510323 1.77704379 1.75072042 1.37206113 1.04244241 2.25412819
 1.82106224 1.85917038 1.66234917 1.29177779 1.8339042  2.27522487
 1.52872073 1.8261141  0.88561054 1.08233898 1.43627801 1.00413607
 4.38564268 2.10272415 0.96396162 0.70759484 0.30695974 0.38009794
 0.61766531 0.48409426 0.52950385 0.05195089 0.74170425 0.68674421
 0.50196806 0.48007925 0.3377652  0.93358761 1.19420855 1.61158896]
[2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3.]
47.60157661582648
